In [1]:
import torch

# Tensor arithmetic with PyTorch

In [6]:
t = torch.tensor(6)
print(t)
print(t.dtype)

tensor(6)
torch.int64


In [8]:
t = torch.tensor(6.)
print(t)
print(t.dtype)

tensor(6.)
torch.float32


Here 6. is a shorthand for 6.0. which is indicate that you want to create a floating point number.

Let's explore more

In [12]:
t = torch.tensor([1,2,3])
print(t)
print(t.dtype)
print(t.shape)

tensor([1, 2, 3])
torch.int64
torch.Size([3])


In [21]:
t = torch.tensor([1.,2,3])
print(t)
print(t.dtype)
print(t.shape)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])


The tensor can contains only same type of data. So when we placed one of them as float it will cast all of them

In [22]:
t1 = torch.tensor([1,2,3])
print(t1)
print(t1.shape)

tensor([1, 2, 3])
torch.Size([3])


In [23]:
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2)
print(t2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [24]:
t3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
print(t3.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
