In [1]:
import numpy
import torch
torch.__version__

'1.5.0'

# Tensor Arithmetic with PyTorch

<h5>Tensor data types

In [2]:
t = torch.tensor(6)
print(t)
print(t.dtype)

tensor(6)
torch.int64


In [3]:
t = torch.tensor(6,dtype=torch.float)
print(t)
print(t.dtype)

tensor(6.)
torch.float32


You can assign your own data type also

In [4]:
t = torch.tensor(6.)
print(t)
print(t.dtype)

tensor(6.)
torch.float32


Here 6. is a shorthand for 6.0. which is indicate that you want to create a floating point number.

Let's explore more

<h5>Tensor shape

In [5]:
t = torch.tensor([1,2,3])
print(t)
print(t.dtype)
print(t.shape)

tensor([1, 2, 3])
torch.int64
torch.Size([3])


In [6]:
t = torch.tensor([1.,2,3])
print(t)
print(t.dtype)
print(t.shape)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])


The tensor can contains only same type of data. So when we placed one of them as float it will cast all of them

In [7]:
t1 = torch.tensor([1,2,3])
print(t1)
print(t1.shape)

tensor([1, 2, 3])
torch.Size([3])


In [8]:
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2)
print(t2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [9]:
t3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)
print(t3.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])


Tensors can have any number of dimensions, and different lengths

let's construct a 5x3 matrix, uninitialized

In [10]:
t = torch.rand(5, 3)
print(t)

tensor([[0.6051, 0.1358, 0.6353],
        [0.2691, 0.3063, 0.6831],
        [0.2838, 0.1827, 0.1648],
        [0.9129, 0.4145, 0.2376],
        [0.2003, 0.8000, 0.4764]])


In [11]:
t = torch.zeros(5, 3, dtype=torch.long)
print(t)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


<h5>Tensor transpose

In [12]:
t = torch.tensor([[1,2,3],[4,5,6]])
print(t)
print(t.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [13]:
# Transpose
t.t()

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [14]:
# Transpose (via permute)
t.permute(-1,0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

<h5>Tensor Reshape with iew

In [15]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Reshape with view

In [16]:
t.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Reshape with view again

In [17]:
t.view(6,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

<h5>Tensor Information

In [18]:
# Some tensor info
print('Tensor shape:', t.shape)   # t.size() gives the same
print('Number of dimensions:', t.dim())
print('Tensor type:', t.type())  

Tensor shape: torch.Size([2, 3])
Number of dimensions: 2
Tensor type: torch.FloatTensor


<h5>Tensor addition</h5>
The element-wise addition of two tensors with the same dimensions results in a new tensor with 
the same dimensions where each scalar value is the element-wise addition of the scalars in the parent tensors.

In [19]:
t1 = torch.rand(4,3)
t2 = torch.rand(4,3)
print(t1)
print(t2)
print(t1 + t2)

tensor([[0.1079, 0.6118, 0.2685],
        [0.7571, 0.8914, 0.6529],
        [0.1761, 0.8397, 0.0274],
        [0.4298, 0.6917, 0.0563]])
tensor([[0.8508, 0.3559, 0.8427],
        [0.3772, 0.0776, 0.1198],
        [0.6341, 0.7408, 0.2053],
        [0.6422, 0.7413, 0.2769]])
tensor([[0.9586, 0.9677, 1.1111],
        [1.1343, 0.9690, 0.7726],
        [0.8103, 1.5804, 0.2328],
        [1.0720, 1.4329, 0.3331]])


<h5>Tensor Product</h5>
Performs a matrix multiplication of the matrices mat1 and mat2.

If matrix1 is a (n×m) tensor, matrix2 is a (m×p) tensor, out will be a (n×p) tensor.

In [20]:
m1 = torch.rand(2,3)
m2 = torch.rand(3,2)
m3 = torch.mm(m1,m2)
print(m1)
print(m2)
print(m3)

tensor([[0.7409, 0.7977, 0.2156],
        [0.0706, 0.5236, 0.7165]])
tensor([[0.0690, 0.4489],
        [0.3888, 0.3288],
        [0.6119, 0.2801]])
tensor([[0.4932, 0.6553],
        [0.6469, 0.4046]])


<h5>PyTorch Tensor To and From Numpy ndarray</h5>

You can easily create a tensors from an ndarray and vice versa. 
These operations are fast, since the data of both structures will share the same memory space, 
and so no copying is involved. This is obviously an efficient approach.

Numpy ndarray to PyTorch tensor

In [21]:
np_a = numpy.random.randn(3,5)
t = torch.from_numpy(np_a)
print(np_a)
print(t)
print(type(np_a))
print(type(t))

[[-0.41749337 -0.00234322 -0.73671071 -0.81345565 -1.17166277]
 [-1.29763645 -1.28002106  1.4760002   0.30410244 -0.32425006]
 [ 1.80540072 -0.80574011 -1.85814052 -0.66605284  0.66771691]]
tensor([[-0.4175, -0.0023, -0.7367, -0.8135, -1.1717],
        [-1.2976, -1.2800,  1.4760,  0.3041, -0.3243],
        [ 1.8054, -0.8057, -1.8581, -0.6661,  0.6677]], dtype=torch.float64)
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


PyTorch tensor to Numpy ndarray

In [22]:
t = torch.rand(3,5)
np_a = t.numpy()
print(t)
print(np_a)
print(type(np_a))
print(type(t))

tensor([[0.9423, 0.7826, 0.3643, 0.9560, 0.3057],
        [0.6873, 0.0147, 0.0791, 0.5373, 0.8679],
        [0.8345, 0.9230, 0.9378, 0.8177, 0.0743]])
[[0.94228536 0.782649   0.36426556 0.9559813  0.30567437]
 [0.68726057 0.01474398 0.07914484 0.5373291  0.86793417]
 [0.8345047  0.9229511  0.93779755 0.8177026  0.07431334]]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


<h5>Tensor operations and gradients</h5>

In [23]:
# Create tensors.
x1 = torch.tensor(2.)
w1 = torch.tensor(5., requires_grad=True)
b = torch.tensor(7., requires_grad=True)

x2 = torch.tensor(2., requires_grad=True)
w2 = torch.tensor(5., requires_grad=True)
b2 = torch.tensor(7., requires_grad=True)

requires_grad indicates whether a variable is trainable. 
By default, requires_grad is False in creating a Variable.

In [24]:
y = w1 * x1 + w2 * x2 + b

In [25]:
print("x1:",x1)
print("x2:",x2)
print("w1:",w1)
print("w2:",w2)
print("b:",b)
print("y:",y)


x1: tensor(2.)
x2: tensor(2., requires_grad=True)
w1: tensor(5., requires_grad=True)
w2: tensor(5., requires_grad=True)
b: tensor(7., requires_grad=True)
y: tensor(27., grad_fn=<AddBackward0>)


It performs the backpropagation starting from a variable. 
In deep learning, this variable often holds the value of the cost function. 
Backward executes the backward pass and computes all the backpropagation gradients automatically

To compute the derivatives, we can call the .backward method on our result y.

In [26]:
y.backward()
print(y)

tensor(27., grad_fn=<AddBackward0>)


The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.
Display gradients

In [27]:
print('dy/dx1:', x1.grad)
print('dy/dx2:', x2.grad)
print('dy/dw1:', w1.grad)
print('dy/dw2:', w1.grad)

dy/dx1: None
dy/dx2: tensor(5.)
dy/dw1: tensor(2.)
dy/dw2: tensor(2.)


Note that x1.grad is None, because x doesn't have requires_grad set to True.